"""Bregman projection via the Frank-Wolfe algorithm.

The research frames "compute the optimal trade" as projecting the current
market price vector onto the arbitrage-free manifold M under a Bregman
divergence generated by the negative entropy (so price moves are weighted
by information content, not raw distance). M has exponentially many
vertices (one per feasible joint outcome), so the projection is computed
with Frank-Wolfe / conditional gradient: each iteration solves a linear
minimisation oracle (an integer program picking the best feasible vertex)
and takes a convex step toward it, growing an active set one vertex at a
time instead of enumerating 2^n outcomes.

This module is a faithful, self-contained implementation of that loop for
the discrete-outcome case. It is used to (a) quantify how far a market is
from arbitrage-free (the Bregman divergence == max extractable profit) and
(b) cross-check the LP trade sizing.
"""
from __future__ import annotations

from dataclasses import dataclass

import numpy as np


def _neg_entropy_grad(p: np.ndarray, eps: float = 1e-12) -> np.ndarray:
    """Gradient of the negative-entropy Bregman generator: log(p) + 1."""
    return np.log(np.clip(p, eps, None)) + 1.0


def bregman_divergence(p: np.ndarray, q: np.ndarray, eps: float = 1e-12) -> float:
    """KL-style Bregman divergence D(p||q) for the neg-entropy generator.

    D(p||q) = sum p*log(p/q) - sum p + sum q  (generalised KL).
    """
    p = np.clip(p, eps, None)
    q = np.clip(q, eps, None)
    return float(np.sum(p * np.log(p / q)) - np.sum(p) + np.sum(q))


@dataclass
class ProjectionResult:
    projection: np.ndarray   # nearest arbitrage-free price vector
    divergence: float        # == max guaranteed profit per unit
    iterations: int
    gap: float               # final Frank-Wolfe duality gap
    active_vertices: int


def frank_wolfe_projection(
    market_price: np.ndarray,
    vertices: np.ndarray,
    max_iter: int = 150,
    tol: float = 1e-6,
) -> ProjectionResult:
    """Project `market_price` onto conv(vertices) under Bregman divergence.

    `vertices` are the payoff vectors of feasible joint outcomes (rows).
    The arbitrage-free set M is their convex hull. We minimise
    D(market_price || x) over x in M via conditional gradient.

    Returns the projection plus the divergence, which equals the maximum
    per-unit guaranteed profit extractable from the mispricing.
    """
    q = market_price.astype(float)
    n_vertices = vertices.shape[0]
    if n_vertices == 0:
        return ProjectionResult(q.copy(), 0.0, 0, 0.0, 0)

    # Start at the centroid of the (so far trivial) active set.
    x = vertices.mean(axis=0).astype(float)
    active = {int(np.random.randint(n_vertices))}

    gap = float("inf")
    it = 0
    for it in range(1, max_iter + 1):
        grad = _neg_entropy_grad(x) - _neg_entropy_grad(q)
        # Linear minimisation oracle: pick feasible vertex minimising <grad, s>.
        scores = vertices @ grad
        s_idx = int(np.argmin(scores))
        s = vertices[s_idx]
        active.add(s_idx)

        # Frank-Wolfe duality gap.
        gap = float(grad @ (x - s))
        if gap <= tol:
            break

        step = 2.0 / (it + 2.0)  # standard diminishing step size
        x = (1.0 - step) * x + step * s

    div = bregman_divergence(q, x)
    return ProjectionResult(
        projection=x,
        divergence=div,
        iterations=it,
        gap=gap,
        active_vertices=len(active),
    )


def max_extractable_profit(market_price: np.ndarray, vertices: np.ndarray) -> float:
    """Convenience wrapper: Bregman distance to the arbitrage-free hull."""
    return frank_wolfe_projection(market_price, vertices).divergence
